<?php

namespace common\models;

use \common\models\base\AccessTokens as BaseAccessTokens;

/**
 * This is the model class for table "access_tokens".
 */
class AccessTokens extends BaseAccessTokens
{
    /**
     * @inheritdoc
     */
    public function rules()
    {
        return parent::rules(); // TODO: Change the autogenerated stub
    }
}
